# Site settings
name: Zohaib Ahmed Butt
title: Zohaib Ahmed Butt | Full-Stack Developer
description: Developer focused on providing beautiful code that meets requirements
url: https://zohaibahmedbutt.github.io/
baseurl: ''
email: zohaibahmedbutt@gmail.com
resume: https://zohaib94.github.io/Resume_Zohaib_Ahmed_Butt_MS(SE)_Tartu.pdf
social:
  - title: email
    url: mailto:zohaibahmedbutt@gmail.com
  - title: instagram
    url: https://instagram.com/zohaib94
  - title: github
    url: https://github.com/zohaib94
  - title: linkedin
    url: https://www.linkedin.com/in/zohaib-ahmed-46197261/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
